name = "fwc26-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "WC2026_KV"
id = "254c1875f5e04b54a1347770eca7c24d"
preview_id = "128380b259c94672b4f3cbc7f1f03ffa"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
CORS_ORIGIN = "https://myangooi.github.io"
